### ISSUE TITLE
workflow is attempting to lint deleted files

### ISSUE THREAD

**Issue by imsteev** [bradennapier/eslint-plus-action#30]
hello! it's me again 😄 

I'm getting a workflow error that says:

```
PR with files detected: someFile,anotherFile
##[error]Error: No files matching 'someFile' were found.
##[error]No files matching 'anotherFile' were found.
```

**Comment by bradennapier** [comment]
What settings are you using?

**Comment by imsteev** [comment]
I agree that `errorOnUnmatchedPattern` defaulted to false should work.. the only setting we've toggled is `reportWarnings` 🤔

**Comment by imsteev** [comment]
@bradennapier are you able to take a look? this issue is coming up quite often for us during things like refactoring. the only workaround to remove the failing check is to manually delete the Workflow results

I was originally going to suggest filtering the files fetched from the PR by checking `file.status === 'deleted'`, but I don't think that is being return from the GraphQL request that is being made

**Comment by bradennapier** [comment]
> @bradennapier are you able to take a look? this issue is coming up quite often for us during things like refactoring. the only workaround to remove the failing check is to manually delete the Workflow results
> 
> I was originally going to suggest filtering the files fetched from the PR by checking `file.status === 'deleted'`, but I don't think that is being return from the GraphQL request that is being made

I was planning to look into this ASAP - that was my expected solution :-P

**Comment by bradennapier** [comment]
@imsteev see the PR #31 - mine works fine when I deleted `src/quick.ts`

**Comment by imsteev** [comment]
@bradennapier our config file looks like:

```js
module.exports = {
  extends: [
    'react-app',
    'prettier',
    'plugin:@typescript-eslint/recommended'
  ],
  plugins: ['react-hooks', 'mocha', 'i18next', '@typescript-eslint'],
  ignorePatterns: ['build/**'],
  rules: {
    ...
  },
  overrides: [
    {
      files: ['*.test.ts', '*.test.tsx', '*.spec.ts'],
      rules: {
        ...
      }
    }
  ]
};
```

and the debug output before running ESLint:
```
[ESLINT] Run With Configuration  {
  extensions: [ '.js', '.jsx', '.ts', '.tsx' ],
  ignore: true,
  useEslintrc: true,
  rulePaths: [],
  errorOnUnmatchedPattern: false,
  fix: false,
  configFile: undefined
}
```

**Comment by imsteev** [comment]
> Also - what version of eslint are you using? Looks like the errorOnUmatchedPattern was added in 6.8.0

oh wait this might be it... we're on 6.7.2

**Comment by imsteev** [comment]
@bradennapier alright bumping the version of ESLint to latest works for me (meaning the workflow passed with a deleted file!)

the downside to this is that I have to add `SKIP_PREFLIGHT_CHECK=true` to ignore CRA's dependency check before a yarn start.

**Comment by bradennapier** [comment]
Cant you use yarn resolutions?

**Comment by bradennapier** [comment]
Ah yeah - quick google shows thats a pretty big overall annoyance people have ... not much can be done there there :-\   I could do a force `yarn add` on eslint after you checkout but that prob would have unwanted side effects :-)

**Comment by bradennapier** [comment]
You could add a command in the workflow right before the linting runs that updates eslint though --

```yaml
name: "lint"
on: 
  # by adding a schedule task to this workflow we will automatically
  # begin serializing read-only runs and handling them. The cron job
  # below is set to run every 15 minutes, GitHub will ignore anything
  # under 10 minutes and run every 10 minutes anyway.
  schedule:
    - cron: '*/15 * * * *'
  pull_request:
    types:
      - opened
      - synchronize
      - closed
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update eslint 
      run: yarn add --dev eslint@6.8.0
      env:
        NODE_ENV: development
    - uses: bradennapier/eslint-plus-action@v3.4.0
      with: 
           reportWarnings: false
```
