### ISSUE TITLE
`TypeError: eslint_1.CLIEngine is not a constructor` in Node 16.11.1

### ISSUE THREAD

**Issue by jfeldstein** [bradennapier/eslint-plus-action#72]
This error: 

```
[ESLINT] Run With Configuration  {
  extensions: [ '.js', '.jsx', '.ts', '.tsx' ],
  ignore: true,
  useEslintrc: true,
  rulePaths: [],
  errorOnUnmatchedPattern: false,
  fix: false,
  configFile: undefined
}
##[error]TypeError: eslint_1.CLIEngine is not a 
##[error]eslint_1.CLIEngine is not a constructor
```

Is caused by the following workflow YML:

```
name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v2
        with:
          node-version: '16.11.1'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: ESLint Plus
        uses: bradennapier/eslint-plus-action@v3

      - name: Run tests 
        run: yarn test
```
