### ISSUE TITLE
Action failing for node > 16

### ISSUE THREAD

**Issue by iamarpitpatidar** [bradennapier/eslint-plus-action#84]
since its using node 16 my actions are failing, please suggest a way to fix this as even `setup-node` isn't working
action config used
```yml
name: Lint Report
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: Lint Report
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Generate Lint Report
      uses: Maggi64/eslint-plus-action@master
```
